### ISSUE TITLE
Why retrieving the post again?

### ISSUE THREAD

**Issue by ahmedabdelfattahuni** [Zaher1307/codersquare#1]
https://github.com/Zaher1307/codersquare/blob/4ace2cb2eadcb37ac1d9277706fc8f1518a61056/src/controllers/posts.js#L32

 If you want to make sure that it was created, just wrap the function body in try/catch and check for exceptions.
 It's always good to wrap your code within try/catch and check for exceptions. (traverse all the functions and try to apply this).

**Comment by Zaher1307** [comment]
I fixed this issue
