### ISSUE TITLE
Error-prone:

### ISSUE THREAD

**Issue by ahmedabdelfattahuni** [Zaher1307/codersquare#2]
https://github.com/Zaher1307/codersquare/blob/4ace2cb2eadcb37ac1d9277706fc8f1518a61056/src/controllers/likes.js#L43

As mentioned in another issue, you are not checking whether the function executed successfully or threw an execption.
Catching exceptions is valuable for logging errors.

**Comment by Zaher1307** [comment]
I fixed this issue
