### ISSUE TITLE
Readability optimization

### ISSUE THREAD

**Issue by ahmedabdelfattahuni** [Zaher1307/codersquare#3]
https://github.com/Zaher1307/codersquare/blob/4ace2cb2eadcb37ac1d9277706fc8f1518a61056/src/controllers/users.js#L43

You seem to be using literal string "bad request ...." a lot, why not creating a general wrapper function that takes an http response code, response message and a _response object_ and internally handles sending the appropriate error message.

Example of that:
`return responseHandler(response, 400, "invalid email")`

**Comment by Zaher1307** [comment]
this issue has been fixed
