### ISSUE TITLE
Thrown error handling

### ISSUE THREAD

**Issue by IslamWalid** [Zaher1307/codersquare#4]
https://github.com/Zaher1307/codersquare/blob/8664bd3b028dfa6a8bc2e209e8b93db75794782d/src/middlewares/authMiddleware.js#L11

- `verify` acts synchronously when callback is not passed to it, there's no need for the `await` statement.
- if the verification failed `verify` will throw an error, you should use it inside try-catch block.

**Comment by Zaher1307** [comment]
this issue has been fixed
